// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dashuyg.Data;

#nullable disable

namespace dashuyg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309093341_Capitano")]
    partial class Capitano
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Roman",
                            OlusturmaTarihi = new DateTime(2026, 3, 9, 12, 33, 40, 962, DateTimeKind.Local).AddTicks(8038)
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bilim",
                            OlusturmaTarihi = new DateTime(2026, 3, 9, 12, 33, 40, 962, DateTimeKind.Local).AddTicks(8074)
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Tarih",
                            OlusturmaTarihi = new DateTime(2026, 3, 9, 12, 33, 40, 962, DateTimeKind.Local).AddTicks(8076)
                        });
                });

            modelBuilder.Entity("Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Kitaplar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Suç ve Ceza",
                            KategoriId = 1,
                            SayfaSayisi = 600,
                            Yazar = "Dostoyevski"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "1984",
                            KategoriId = 1,
                            SayfaSayisi = 328,
                            Yazar = "George Orwell"
                        });
                });

            modelBuilder.Entity("Kitap", b =>
                {
                    b.HasOne("Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
